name: "🐞 Bug Report"
description: "Did you find a bug in Happy Elementor Addons, and can reproduce it consistently after troubleshooting it? Report it here."
labels: ["status/awaiting_triage"]
body:
    - type: markdown
      attributes:
          value: |
              **👋 Hello, welcome to the Happy Elementor Addons Bug Reports!**
              # ⚠️ BEFORE POSTING READ THIS CAREFULLY
              ## 🐞 Please only use this form to report validated Happy Elementor Addons Bugs.
              ### 🛟 Need Help, Guidance, Assistance, or Support? <br>[Click here to get support](https://happyaddons.com/happy-support/).

              ✳️ All fields are required!
    - type: checkboxes
      id: prerequisites
      attributes:
          label: "Prerequisites"
          options:
              - label: "I have searched for similar issues in open and closed tickets and cannot find a duplicate."
                required: true
              - label: "I have troubleshooted my issue, and it still exists against the latest stable version of Elementor & Happy Elementor Addons."
                required: true
    - type: markdown
      attributes:
          value: |
              <br>

              ### 💬 Provide a Detailed Description
              Please describe the problem in detail, provide examples, screenshots, and related links.
    - type: textarea
      id: description
      validations:
          required: true
      attributes:
          label: "Description"
          description: "Please help us understand in detail what problems you are experiencing."
    - type: markdown
      attributes:
          value: |
              <br>

              ### 👣 Steps to Reproduce
              Enumerate all the steps needed to reproduce the issue in detail so we can replicate it in our environment. 
              - Be thorough. We will only be able to reproduce your issue if you thoroughly explain all the steps to replicate it. 
              - If Possible, please **share a screen recording**. It helps a lot!
    - type: textarea
      id: steps_to_reproduce
      validations:
          required: true
      attributes:
          label: "Steps to reproduce"
          description: "Provide steps that we can recreate on our own."
          placeholder: "1. ... \n2. ... \n3. ..."
    - type: markdown
      attributes:
          value: |
              <br>

              ### 🧐 Expected Behavior
              Describe the expected behavior to help identify the root of the issue.
    - type: textarea
      id: expected_behavior
      validations:
          required: true
      attributes:
          label: "Expected behavior"
          description: "Please help us understand what you are expecting to happen."
          placeholder: "1. ... \n2. ... \n3. ..."
    - type: markdown
      attributes:
          value: |
              <br>

              ### 🕵️ Isolate the problem and Validate your issue
              - Deactivate all plugins _**except Elementor, Happy Elementor Addons (and Elementor Pro, Happy Elementor Addons Pro)**_, and temporarily change the theme to the **[Hello Elementor theme](https://wordpress.org/themes/hello-elementor/)**.
              - Verify if your problem happens when only the Elementor, Happy Elementor Addons (and Elementor Pro, Happy Elementor Addons Pro) plugins are active while also using the Hello Elementor theme.
    - type: checkboxes
      id: isolating_the_problem
      attributes:
          label: "Isolating the problem"
          options:
              - label: "This bug happens when only the Elementor, Happy Elementor Addons (and Elementor Pro, Happy Elementor Addons Pro) plugins are active."
                required: true
              - label: "This bug happens with the Hello Elementor theme active."
                required: true
              - label: "I can reproduce this bug consistently by following the steps I described above."
                required: true
    - type: markdown
      attributes:
          value: |
              <br>

              ### 💾 Elementor System Info
              **⚠️ <ins>This field is REQUIRED</ins>**
              - Please copy and paste the **<ins>full Elementor System Info</ins>** report from your WordPress **`Dashboard`** > **`Elementor`** > **`System Info`** page (available at the bottom of the page). <br>**We won't accept issues without it. [Learn how to copy it here](https://elemn.to/help-system-info).**
    - type: textarea
      id: system_info
      validations:
          required: true
      attributes:
          label: "Elementor System Info"
          description: "Redact or remove sensitive information (admin email, website links, or root paths) if necessary. Keep other details, as these are vital for understanding your problem and recreating it correctly."
          placeholder: "== Server Environment == \n== WordPress Environment == \n== Theme == \n== User == \n== Active Plugins == \n== Elements Usage == \n== Settings == \n== Features == \n== Integrations == \n== Elementor Experiments == \n== Log == \n== Elementor - Compatibility Tag == \n== Elementor Pro - Compatibility Tag =="
          render: txt
    - type: markdown
      attributes:
          value: |
              <br>

              ### 📃 Agreement
              ⚠️ **Please follow all the instructions above** and fill in all the required fields with valid information. 
              ⛔ **As a gentle reminder, we may close issues that do not comply with these guidelines without action.**
    - type: checkboxes
      id: final_agreement
      attributes:
          label: "Agreement"
          options:
              - label: "I agree that my issue may be closed without action if it doesn't meet all the requirements."
                required: true
    - type: markdown
      attributes:
          value: |
              <br>

              ---
              ### 🙏 Thank you for contributing and helping make Happy Elementor Addons better.